### ISSUE TITLE
Server sync issues: error in syncing space breaks entire bulk sync + deleting space that doesn't exist should be allowed

### ISSUE THREAD

**Issue by naraesk** [turtl/tracker#140]
I'm using v0.7.0-rc5 on Arch Linux. That's the first RC that runs without problems on my system, haven't noticed any critical things so far. Well done! :-)

I've noticed only some small issues, e.g., settings for spaces are not stored properly. 

- "Set this as your default space" has no effect at all. After closing and reopening turtl the old space is the defautl space again. 
- Same for renaming spaces

Console output contains "ignored incoming syncs", might be relevant?

> $ /opt/turtl/turtl 
2018-08-21T16:24:20 - [INFO][turtl_core] main::init() -- created data folder: /home/naraesk/.config/Turtl/core
2018-08-21T16:24:20 - [INFO][turtl_core] main::start() -- begin
2018-08-21T16:24:20 - [INFO][turtl_core::messaging] messaging::start() -- main loop
2018-08-21T16:24:20 - [INFO][turtl_core::messaging] messaging::ui_event() -- messaging:ready
2018-08-21T16:24:20 - [INFO][turtl_core::dispatch] dispatch(1): app:api:set-endpoint
2018-08-21T16:24:20 - [INFO][turtl_core::dispatch] dispatch(2): user:login-from-saved
2018-08-21T16:24:20 - [INFO][turtl_core::models::user] User::restore_login() -- restored login from "/home/naraesk/.config/Turtl/core/39.login"
2018-08-21T16:24:21 - [INFO][turtl_core::api] api::call() -- res(4): RawStatus(200, "OK") POST /auth
2018-08-21T16:24:23 - [INFO][turtl_core::api] api::call() -- res(414): RawStatus(200, "OK") GET /users/39
2018-08-21T16:24:23 - [INFO][turtl_core::messaging] messaging::ui_event() -- user:login
2018-08-21T16:24:23 - [INFO][turtl_core::dispatch] dispatch(3): sync:start
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- incoming init (run 1)
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- outgoing init (run 1)
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- files:outgoing init (run 1)
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- outgoing main loop
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- files:incoming init (run 1)
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- files:outgoing main loop
2018-08-21T16:24:23 - [INFO][turtl_core::sync] sync::runner() -- files:incoming main loop
2018-08-21T16:24:24 - [INFO][turtl_core::api] api::call() -- res(30): RawStatus(200, "OK") GET /sync?sync_id=16624&immediate=1
2018-08-21T16:24:24 - [INFO][turtl_core::sync::incoming] SyncIncoming.update_local_db_from_api_sync() -- ignored 0 incoming syncs
2018-08-21T16:24:24 - [INFO][turtl_core::dispatch] dispatch::dispatch_event() -- sync:connected
2018-08-21T16:24:24 - [INFO][turtl_core::messaging] messaging::ui_event() -- sync:connected
2018-08-21T16:24:24 - [INFO][turtl_core::sync] sync::runner() -- incoming main loop
2018-08-21T16:24:24 - [INFO][turtl_core::dispatch] dispatch::dispatch_event() -- sync:incoming
2018-08-21T16:24:24 - [INFO][turtl_core::sync] sync::start() -- all sync threads started
2018-08-21T16:24:24 - [INFO][turtl_core::messaging] messaging::ui_event() -- profile:loaded
2018-08-21T16:24:24 - [INFO][turtl_core::messaging] messaging::ui_event() -- profile:indexed
2018-08-21T16:24:24 - [INFO][turtl_core::dispatch] dispatch(4): profile:load
2018-08-21T16:24:24 - [INFO][turtl_core::dispatch] dispatch(5): profile:find-notes
2018-08-21T16:24:34 - [INFO][turtl_core::dispatch] dispatch(6): profile:sync:model
2018-08-21T16:24:34 - [INFO][turtl_core::messaging] messaging::ui_event() -- sync:update
2018-08-21T16:24:34 - [INFO][turtl_core::messaging] messaging::ui_event() -- sync:update
2018-08-21T16:24:34 - [INFO][turtl_core::sync::outgoing] SyncOutgoing.run_sync() -- sending 2 sync items
2018-08-21T16:24:36 - [INFO][turtl_core::api] api::call() -- res(1364): RawStatus(200, "OK") POST /sync
2018-08-21T16:24:36 - [INFO][turtl_core::sync::outgoing] SyncOutgoing.run_sync() -- got 2 successes, 0 failed, 0 blocked syncs
2018-08-21T16:24:36 - [INFO][turtl_core::messaging] messaging::ui_event() -- sync:outgoing:complete
2018-08-21T16:24:39 - [INFO][turtl_core::api] api::call() -- res(1311): RawStatus(200, "OK") GET /sync?sync_id=16624&immediate=0
2018-08-21T16:24:39 - [INFO][turtl_core::sync::incoming] SyncIncoming.update_local_db_from_api_sync() -- ignored 2 incoming syncs
2018-08-21T16:24:39 - [INFO][turtl_core::dispatch] dispatch::dispatch_event() -- sync:connected
2018-08-21T16:24:39 - [INFO][turtl_core::dispatch] dispatch::dispatch_event() -- sync:incoming

**Comment by orthecreedence** [comment]
Can you check `Settings -> Sync info` and tell me if you have anything in there? This shows pending sync items that have yet to be sent to the server. Generally it should be empty if things are working. It will (hopefully) show you the error if something is wrong.

**Comment by naraesk** [comment]
It says "Connected" and "You have 79 pending sync item(s)". Followed by 79 items (keychain, spaces, boards, and nodes) with status "Ready to sync". I don't see any error messages.

 I've created a new account and a new keychain with RC5.

**Comment by orthecreedence** [comment]
Are any of the sync items in an error state?

**Comment by naraesk** [comment]
It just looks like this:

![screenshot_20180822_194020](https://user-images.githubusercontent.com/7393797/44480307-352d9700-a643-11e8-8478-83113cac8e97.png)

**Comment by naraesk** [comment]
Debug log has a lot of entries like this:

>2018-08-22T19:41:46 - [ERROR][turtl_core::sync] sync::runner() -- outgoing: main loop: {"err":{"message":{"error":{"message":"you don't have access to space 0165546 ... "}},"subtype":"Forbidden","type":"api"},"file":"src/api.rs","line":224,"wrapped":true}
2018-08-22T19:41:47 - [INFO][turtl_core::sync::outgoing] SyncOutgoing.run_sync() -- sending 79 sync items

The number after space is much longer than 0165546, censored it just in case ;-)

**Comment by orthecreedence** [comment]
This is the server log:
```
info: sync.bulk_sync() -- user 39: syncing 4 items:  keychain.delete=1, space.delete=1, board.add=1, note.edit=1
error: sync.bulk_sync() --  Error: you don't have access to space 016554648e807f284f12c64249684813db9ae4cb7e34306bf955fb6d3be1c2178db4377d94ea0000
    at Object.forbidden (/var/www/turtl/server/helpers/error.js:5:13)
    at /var/www/turtl/server/models/space.js:39:32
    at tryCatcher (/var/www/turtl/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/www/turtl/server/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/var/www/turtl/server/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/var/www/turtl/server/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/var/www/turtl/server/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/var/www/turtl/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/var/www/turtl/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/var/www/turtl/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
error: tres.err -- (uid 39): you don't have access to space 016554648e807f284f12c64249684813db9ae4cb7e34306bf955fb6d3be1c2178db4377d94ea0000
info: ::ffff:127.0.0.1 "POST /sync" 403 135
```

Apparently it thinks you do not own the space that's being edited. I might need to take a deeper look.

**Comment by orthecreedence** [comment]
Ok, I see the issue. Looks like it did delete the space in an earlier sync, then the sync as a whole failed (probably a closed connection caused previously) and now it keeps trying to resend the same sync over and over (and delete a space that doesn't exist). I need to make a change to the server that allows a delete on a space that doesn't exist. I'll let you know when this is done.

**Comment by naraesk** [comment]
Thought the root cause might be that the keychain could not by synced. Is it possible to sync notes and spaces without a synced keychain?

Thanks for having a look at it.Will test the fix as soon as it is available.

**Comment by orthecreedence** [comment]
The keychain is actually syncing fine, but the space being synced directly after it is the one failing. Oddly, the server should accept the keychain sync and return the rest as errors. I may need to fix that first (so the server actually handles the error correctly instead of throwing out the entire sync), then push the change to allow deleting and already-deleted space.

**Comment by orthecreedence** [comment]
This should be fixed. Did two things: one sync item failing won't crash the entire sync (and confuse the client) and secondly, deleting a space that's already deleted will just do nothing (not throw an error).

**Comment by naraesk** [comment]
You have 0 pending sync item(s)

Thanks. :-)
