### ISSUE TITLE
Cannot start the RC6 on Windows 10

### ISSUE THREAD

**Issue by PxSonny** [turtl/tracker#148]
Hi, 

As you can see in the screenshot below: 

![image](https://user-images.githubusercontent.com/6723977/44617277-533d0680-a892-11e8-9511-9f3f6d522ace.png)

I have this error message:
```
Error: Dynamic Linking Error: Win32 error 193
    at new DynamicLibrary (C:\Program Files\Turtl\resources\app\node_modules\ffi\lib\dynamic_library.js:74:11)
    at Object.Library (C:\Program Files\Turtl\resources\app\node_modules\ffi\lib\library.js:45:12)
    at Object.<anonymous> (C:\Program Files\Turtl\resources\app\lib\node\core.js:8:22)
    at Object.<anonymous> (C:\Program Files\Turtl\resources\app\lib\node\core.js:71:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
```

Hoping it can help to progress onto the release :)

Cheers,
Sonny

**Comment by orthecreedence** [comment]
This should be fixed in RC7: https://github.com/turtl/desktop/releases !

If not let me know and I will reopen.

**Comment by PxSonny** [comment]
It's fixed, awesome thanks.
