### ISSUE TITLE
TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by huguesgr** [turtl/tracker#260]
Hello,

I am encountering an issue when trying to update my turtl server with the latest Github code.
The code from early november works fine.
The database is PostgreSQL.

Logs:
```
debug: db: query:  SELECT user_id FROM spaces_users WHERE space_id = $1 0=0166215fbbcd00cccaac81bca949fc5ab48599536116f5c61d36040d5b182dfa3142ac767c410019
debug: db: query:  INSERT INTO sync ("user_id","type","item_id","action") VALUES ($1,$2,$3,$4) RETURNING sync.*; 0=1, 1=note, 2=016621608aed00cccaac81bca949fc5ab48599536116f5c61d36040d5b182dfa3142ac767c410038, 3=edit
debug: db: query:  INSERT INTO sync_users ("sync_id","user_id") VALUES ($1,$2) RETURNING sync_users.*; 0=565, 1=1
debug: sync.bulk_sync() -- sync item done:  01679250296d9fe9efd126c9892f17892de173d79a0de30500085d9f9e4b4717ea6b37a7db420abc
debug: sync.bulk_sync() -- sync complete
error: tres.err -- (uid 1): TypeError: Cannot read property 'then' of null
    at /app/models/sync.js:455:4
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
info: ::ffff:172.23.0.1 "POST /sync" 500 59
debug: db: query:  SELECT * FROM users WHERE username = $1 0=XXXXXXXXXXXX@XXXXX.XXX
debug: db: query:  SELECT
	s.*
FROM
	sync s, sync_users su
WHERE
	s.id = su.sync_id AND
	su.user_id = $1 AND
	s.id > $2
ORDER BY
	s.id ASC 0=1, 1=526
```

**Comment by orthecreedence** [comment]
Sorry about that, this should be fixed now.
