### ISSUE TITLE
Panic during migration

### ISSUE THREAD

**Issue by orthecreedence** [turtl/tracker#275]
Here's the 'trace:

```
2018-12-30T11:05:37 - [DEBUG][migrate] migrate::decrypt_profile() -- decrypted keychain 015ed506045c83fc9fb59fb480fb7accf268a2e6fe6a458b7b29ae4d32d1b6ac27b4b9e50e59007b
2018-12-30T11:05:37 - [INFO][turtl_core::messaging] messaging::ui_event() -- migration-event
2018-12-30T11:05:37 - [DEBUG][migrate] migrate::decrypt_profile() -- decrypted keychain 015ed508022383fc9fb59fb480fb7accf268a2e6fe6a458b7b29ae4d32d1b6ac27b4b9e50e5901a9
2018-12-30T11:05:37 - [INFO][turtl_core::messaging] messaging::ui_event() -- migration-event
2018-12-30T11:05:37 - [DEBUG][migrate] migrate::decrypt_profile() -- decrypted keychain 016479c6f8c883fc9fb59fb480fb7accf268a2e6fe6a458b7b29ae4d32d1b6ac27b4b9e50e590083
2018-12-30T11:05:37 - [INFO][turtl_core::messaging] messaging::ui_event() -- migration-event
2018-12-30T11:05:37 - [DEBUG][migrate] migrate::decrypt_profile() -- decrypted keychain 0161a67f779f9844add7a83c5b95c3e8118c8e6e9aad382a151bbb8d661aa6d68be7fbc050c2006d
2018-12-30T11:05:37 - [INFO][turtl_core::messaging] messaging::ui_event() -- migration-event
2018-12-30T11:05:37 - [ERROR][panic] thread 'dispatch:msg' panicked at 'assertion failed: key.len() == 16 || key.len() == 24 || key.len() == 32': migrate\rust-crypto\src\aes_gcm.rs:23
stack backtrace:
   0:         0x620e6c3a - turtlc_free_err
   1:         0x620e4693 - turtlc_free_err
   2:         0x620e3bdd - turtlc_free_err
   3:         0x626749f1 - carrier_free
   4:         0x62080ef8 - turtlc_free_err
   5:         0x620a0eb1 - turtlc_free_err
   6:         0x62041c9f - turtlc_free_err
   7:         0x6206308a - turtlc_free_err
   8:         0x62031dcd - turtlc_free_err
   9:         0x61e03f0a - <no info>
  10:         0x61e08b7e - <no info>
  11:         0x61e6d08b - turtlc_free_err
  12:         0x61e34008 - <no info>
  13:         0x61f82c3f - turtlc_free_err
  14:         0x626b57f9 - carrier_free
  15:         0x61e3e4da - <no info>
  16:         0x61ea3778 - turtlc_free_err
  17:         0x61f8298f - turtlc_free_err
  18:         0x626b57f9 - carrier_free
  19:         0x61dfe822 - <no info>
  20:         0x626aa5f7 - carrier_free
  21:         0x62674d29 - carrier_free
  22:     0x7ff835e07e94 - BaseThreadInitThunk
2018-12-30T11:05:37 - [ERROR][turtl_core::dispatch] dispatch::process() -- panic: no information available
```

Looks like data corruption resulting in a bad key. Or it's possible this is an attack of the old weird data formats before v0.6.4's v4/v5 encryption when keys were UTF8 encoded and other weird shit happened.

I believe I handled all these nuances, but seems I might have to explicitely check the key length before passing it into the function so it doesn't blow a gasket and wreck the whole migration (although I suspect if I report-and-continue, all this user's data might suffer fromt he same problem).

**Comment by orthecreedence** [comment]
And another:

```
2019-02-08T14:02:38 - [ERROR][panic] thread 'dispatch:msg' panicked at 'assertion failed: key.len() == 16 || key.len() == 24 || key.len() == 32': migrate\rust-crypto\src\aes_gcm.rs:23
stack backtrace:
   0:         0x620e6c3a - turtlc_free_err
   1:         0x620e4693 - turtlc_free_err
   2:         0x620e3bdd - turtlc_free_err
   3:         0x626749f1 - carrier_free
   4:         0x62080ef8 - turtlc_free_err
   5:         0x620a0eb1 - turtlc_free_err
   6:         0x62041c9f - turtlc_free_err
   7:         0x6206308a - turtlc_free_err
   8:         0x62031dcd - turtlc_free_err
   9:         0x61e03f0a - <no info>
  10:         0x61e08b7e - <no info>
  11:         0x61e6d08b - turtlc_free_err
  12:         0x61e34008 - <no info>
  13:         0x61f82c3f - turtlc_free_err
  14:         0x626b57f9 - carrier_free
  15:         0x61e3e4da - <no info>
  16:         0x61ea3778 - turtlc_free_err
  17:         0x61f8298f - turtlc_free_err
  18:         0x626b57f9 - carrier_free
  19:         0x61dfe822 - <no info>
  20:         0x626aa5f7 - carrier_free
  21:         0x62674d29 - carrier_free
  22:     0x7ff9b95f3034 - BaseThreadInitThunk
2019-02-08T14:02:38 - [ERROR][turtl_core::dispatch] dispatch::process() -- panic: no information available
```

This looks like it's becoming a popular problem.

**Comment by orthecreedence** [comment]
Note that this should be "fixed" now (https://github.com/turtl/core-rs/commit/9e5cab5992d675c43174773e087adead077b2c47). The keys are still going to be malformed (and if anyone wants to give me their login so I can test this reliably for a real fix please feel free) but the migration shouldn't choke so horribly on it anymore (no more panics). So for now marking this closed.
