### ISSUE TITLE
server ./scripts/init-db.sh not working

### ISSUE THREAD

**Issue by mammique** [turtl/tracker#363]
Hello, I followed the installation instructions for the server, but the script for initializing the DB doesn't work. I assume it is at the `node` level, I've added the `--trace-warnings` as suggested by the script to get more debug details:

```
/opt/turtl/server# ./scripts/init-db.sh
- running DB schema
(node:6230) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Object.exports.setLevels (/opt/turtl/server/node_modules/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/opt/turtl/server/node_modules/winston/lib/winston.js:83:8)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
(node:6230) Warning: Accessing non-existent property 'loglevel' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Object.<anonymous> (/opt/turtl/server/helpers/log.js:7:24)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/turtl/server/helpers/config.js:3:13)

```

My `node` version is 14.0.0. Here is the output of the installation script, several warnings were made:

```
/opt/turtl/server# npm install
npm WARN lifecycle turtl-server@0.1.3~preinstall: cannot run in wd turtl-server@0.1.3 bash scripts/install-plugins.sh (wd=/opt/turtl/server)
npm WARN deprecated request@2.81.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm notice created a lockfile as package-lock.json. You should commit this file.
added 156 packages from 177 contributors and audited 240 packages in 12.823s
found 23 vulnerabilities (7 low, 6 moderate, 10 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

What should I do next?

Thank you,

Camille.

**Comment by akadaedalus** [comment]
Hi, I noticed my turtl server failed to authenticate (times out).  I eventually traced it down to issues with a Node 14.4 upgrade, and a downgrade to 12.16.1 fixed it for me.  I got the padLevels error but not the loglevel error.  Basic API calls were working but authentication was not responding.
