### ISSUE TITLE
Update core/desktop build instructions in READMEs

### ISSUE THREAD

**Issue by JosuGZ** [turtl/tracker#98]
I've been trying to build the desktop app and it seems the setup instructions are outdated/incomplete, I've found this problems so far:

- Desktop
  - [I can't do npm intall on node v10.4.0](https://github.com/turtl/tracker/issues/97)
  - `core-js` needs to be renamed to `core`
  - Something else is missing, since the app runs but it only shows `turtl` and a broken image ->
    ```
    Error: ENOENT: no such file or directory, open 'libsodium.so.18'
        at Object.fs.openSync (fs.js:652:18)
        at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
        at fs.readFileSync (fs.js:553:33)
        at fs.readFileSync (ELECTRON_ASAR.js:508:29)
        at new DynamicLibrary (/home/mint/Desktop/turtl/desktop/node_modules/ffi/lib/dynamic_library.js:67:21)
        at Object.Library (/home/mint/Desktop/turtl/desktop/node_modules/ffi/lib/library.js:45:12)
        at Object.<anonymous> (/home/mint/Desktop/turtl/desktop/lib/node/core.js:6:21)
        at Object.<anonymous> (/home/mint/Desktop/turtl/desktop/lib/node/core.js:59:3)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
    ```
    - This helps: `export LD_LIBRARY_PATH=/home/mint/Desktop/turtl/core/libsodium-1.0.12/src/libsodium/.libs`
  - I have a `config is not defined` both in routes.js and auth.js -> If I move `<script src="../config.js"></script>` up inside `build/index.html` it works.

- Core-rs
  - I need to install `cargo`, I don't know what that is
  - The url for downloading libsodium is outdated, this one works `https://github.com/jedisct1/libsodium/releases/download/1.0.12/libsodium-1.0.12.tar.gz`
  - This has seemed to work (after building libsodium, instead of copying files) -> `echo "export SODIUM_LIB_DIR := ./libsodium-1.0.12/src/libsodium/.libs/" > vars.mk`

**Comment by JosuGZ** [comment]
Oh I see I've missed the part where it says `# make sure you set up core-rs based on its own setup: https://github.com/turtl/core-rs`, I'll update the issue soon.

**Comment by orthecreedence** [comment]
`core-rs` is a [Rust](https://www.rust-lang.org/en-US/) library. If you [install Rust using rustup](https://rustup.rs/), you'll have `cargo` installed for you.

Then, you should be able to do `make run` in `desktop` and it will build everything (assuming you have libsodium installed properly) and move the build library to the proper location.

I'll try to get more up to date docs on this written.

**Comment by JosuGZ** [comment]
Thanks for your answer and sorry for taking soo long to notice about it. I was actually able to build everything with the steps I placed on this issue, I think the most important one is this: `If I move <script src="../config.js"></script> up inside build/index.html it works.`
